name: Build ROM
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Docker SGDK
        uses: addnab/docker-run-action@v3
        with:
          image: jdesiloniz/sgdk:latest
          options: -v ${{ github.workspace }}:/project -w /project
          run: |
            make clean
            make
            ls -l out
      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: rom
          path: out/rom.bin
